### Tomcat
server.port: 8585

### Spring Security
security:
  enable:
    csrf: false

### Service API
service.api:
  major.version: v0
  version: 0.0.1
  title: ${spring.application.name}
  selector: /**
  docket.custom: true
  description: Middleware optimization layer is a proxy for maintaining stable server part for all underlying backend systems

### SpringDoc settings
springdoc.swagger-ui.disable-swagger-default-url: true

spring:
  main:
    allow-circular-references: true
  application:
    name: Middleware optimization layer for enterprise solution
  ### DB
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma_db
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: dbuser
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
#  ### Liquibase Migration Tool
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    parameters:
#      schema-name: public

#full-text search
hibernate.search.default:
  directory_provider: filesystem
  indexBase: /data/index/default

### App configs
#mail.ru
app:
  server:
    basePath: http://localhost:${server.port}
# Pagination
  pagination:
    defaultPageValue: 0
# JWT
  jwtSecret: middlewareAppSecretKey111222333
  jwtExpirationMs: 86400000
# Services URLs
  services:
    customerServiceUrl: http://localhost:8584
    orderServiceUrl: http://localhost:8583
    catalogServiceUrl: http://localhost:8582



### Circuit breaker config
resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      example:
        base-config: shared
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true
