### Tomcat
server.port: 8583

### Service API
service.api:
  major.version: v0
  version: 0.0.1
  title: ${spring.application.name}
  selector: /**
  docket.custom: true
  description: Order management service is responsible for CRUD operations on orders data

### SpringDoc settings
springdoc.swagger-ui.disable-swagger-default-url: true

spring:
  main:
    allow-circular-references: true
  application:
    name: Order management service for enterprise solution
  ### DB
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma_db
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: dbuser
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        default_schema: order_schema
#  ### Liquibase Migration Tool
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    parameters:
#      schema-name: public

#full-text search
hibernate.search.default:
  directory_provider: filesystem
  indexBase: /data/index/default

### App configs
#mail.ru
app:
  server:
    basePath: http://localhost:${server.port}
  # Pagination
  pagination:
    defaultPageValue: 0

